<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
جرم‌شناسی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
هدف شما در این مسئله، ایجاد یک مدل پیش‌بینی است که می‌تواند از داده‌های تاریخی حوادث جدید را در یکی از چندین دسته جرم طبقه‌بندی کند. این مدل باید به سازمان‌های مجری قانون کمک کند تا الگوهای رفتار مجرمانه را شناسایی کرده و تصمیمات آگاهانه‌تری در مورد استراتژی‌های پیشگیری از جرم در لس‌آنجلس بگیرند.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
مجموعه داده آموزشی شامل 84113 سطر است که در جدول زیر، توضیحات هر ستون آمده است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|DR_NO| یک شناسه‌ی منحصر به فرد برای هر گزارش جرم|
|Date Rptd| تاریخ گزارش جنایت|
|DATE OCC| تاریخ وقوع جرم|
|TIME OCC| زمان وقوع جرم|
|AREA| کد منطقه‌ای که جرم در آن رخ داده است|
|AREA NAME| نام منطقه‌ای که جرم در آن رخ داده است|
|Rpt Dist No| شماره‌ی منطقه‌ی گزارش‌دهنده|
|Crm Cd| کد جرم که نشان‌دهنده‌ی دسته‌ی جرم است (این ستون، متغیر هدف است)|
|Crm Cd Desc| شرح جرم|
|Mocodes| کدهای نشان‌دهنده‌ی روش مورد استفاده برای ارتکاب جرم|
|Vict Age| سن قربانی|
|Vict Sex| جنسیت قربانی|
|Vict Descent| قومیت/تبار قربانی|
|Premis Cd| کد نوع محل وقوع جرم|
|Premis Desc| شرحی از محل|
|Weapon Used Cd| کد نوع سلاح مورد استفاده در جرم|
|Weapon Desc| شرحی از سلاح مورد استفاده|
|Status| وضعیت پرونده (به عنوان مثال، در دست بررسی، بسته‌شده)|
|Status Desc| شرح وضعیت پرونده|
|Crm Cd 1، Crm Cd 2، Crm Cd 3، Crm Cd 4| کدهای جرم اضافی در صورتی که حادثه شامل چندین جرم باشد|
|LOCATION| طول و عرض جغرافیایی جنایت|
|Cross Street| نزدیکترین چهارراه به محل وقوع جرم|
|LAT| مختصات عرض جغرافیایی جرم|
|LON| مختصات طول جغرافیایی جرم|

    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    مجموعه‌داده‌ی آزمایش نیز مانند مجموعه‌ی آموزش است با این تفاوت که ستون <code>Crm Cd</code> که متغیر هدف مسئله است را در خود ندارد. همچنین ستون‌های <code>Crm Cd 1</code> و <code>Crm Cd 2</code> و  <code>Crm Cd 3</code> و <code>Crm Cd 4</code> و <code>Crm Cd Desc</code> که اطلاعات مستقیم در مورد متغیر هدف دارند را نیز در خود ندارد. مجموعه‌داده‌ی آزمایش 9346 سطر و 21 ستون دارد.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
 معیار ارزیابی مورد استفاده در داوری این مسئله، امتیاز <code>F1 Macro</code> است که دقت و بازیابی را در تمام دسته‌های جرم به صورت متعادل‌شده بررسی می‌کند. بر خلاف دقت، که می تواند توسط داده‌های نامتعادل تغییر کند، امتیاز <code>F1 Macro</code>، امتیاز <code>F1</code> را برای هر دسته‌ی جرم به طور مستقل محاسبه می‌کند و سپس میانگین آن‌ها را محاسبه می‌کند. این معیار تضمین می‌کند که عملکرد در دسته‌های جرایم کم‌تکرار اهمیت یکسانی دارد. این ویژگی این معیار را برای پیش‌بینی انواع مختلف جرایم، صرف نظر از فراوانی آنها در مجموعه‌داده، مناسب می‌سازد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    از مدل خود برای پیش‌بینی نمونه‌های موجود در داده‌ی تست استفاده کنید و نتایج را در قالب جدولی (<code>dataframe</code>) به شکل زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: center;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|------|---|
|Crm Cd|کد جرم پیش‌بینی‌شده|
    
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اسم دیتافریم باید <i>submission</i> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل ۱ ستون با اسم <i>Crm Cd</i> است و ? سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، مقادیر ستون <i>Crm Cd</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: center;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|Crm Cd|
|-----|
|210|
|420|
|930|
|624|
|420|

</font>
</div>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler, MultiLabelBinarizer
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier

In [6]:
df = pd.read_csv("train.csv", parse_dates=["Date Rptd", "DATE OCC"])
X_test = pd.read_csv("test.csv", parse_dates=["Date Rptd", "DATE OCC"])
df

C:\Users\Webhouse\AppData\Local\Temp\ipykernel_5296\540890743.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("train.csv", parse_dates=["Date Rptd", "DATE OCC"])
C:\Users\Webhouse\AppData\Local\Temp\ipykernel_5296\540890743.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("train.csv", parse_dates=["Date Rptd", "DATE OCC"])
C:\Users\Webhouse\AppData\Local\Temp\ipykernel_5296\540890743.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  X_test = pd.read_csv("test.csv", parse_dates=["Date Rptd", "DATE OCC"])
C:\Users\Webhouse\AppData\Local\Temp\ipykernel_5296\540890743.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  X_test = pd.read_csv("test.csv", parse_dates=["Date Rptd", "DATE OCC"])

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,201516407,2020-10-17,2020-10-15,2100,15,N Hollywood,1581,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4300 WHITSETT AV,NaN,34.1486,-118.4052
1,200700622,2020-03-24,2020-03-24,1430,7,Wilshire,705,626,INTIMATE PARTNER - SIMPLE ASSAULT,0416 1814 1402,...,AA,Adult Arrest,626.0,998.0,NaN,NaN,800 N ALTA VISTA BL,NaN,34.0853,-118.3475
2,200312712,2020-06-14,2020-06-14,1030,3,Southwest,362,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1251 1259 2024 1815 0554 0334 0913 0400 1402,...,JA,Juv Arrest,230.0,NaN,NaN,NaN,4600 OBAMA BL,NaN,34.0170,-118.3477
3,201515083,2020-09-12,2020-09-08,1528,15,N Hollywood,1585,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0325 0216,...,IC,Invest Cont,341.0,NaN,NaN,NaN,11200 W VENTURA BL,NaN,34.1430,-118.3727
4,200817552,2020-12-14,2020-12-14,805,8,West LA,853,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1822,...,AA,Adult Arrest,740.0,NaN,NaN,NaN,BARRINGTON,NEBRASKA,34.0445,-118.4491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84108,201207833,2020-02-25,2020-02-25,2100,12,77th Street,1211,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1822 0400 0411 0906,...,IC,Invest Cont,230.0,NaN,NaN,NaN,SLAUSON AV,7TH AV,33.9891,-118.3247
84109,201208587,2020-03-06,2020-03-06,920,12,77th Street,1273,626,INTIMATE PARTNER - SIMPLE ASSAULT,2000 0913 1813 0337 0444,...,IC,Invest Cont,626.0,NaN,NaN,NaN,2000 W MANCHESTER AV,NaN,33.9600,-118.3134
84110,201819827,2020-10-31,2020-10-31,30,18,Southeast,1842,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1822 1300 1309 0416 0400 1206 2033,...,IC,Invest Cont,230.0,NaN,NaN,NaN,111TH ST,SAN PEDRO,33.9348,-118.2695
84111,221319440,2022-10-17,2020-05-14,2100,13,Newton,1367,624,BATTERY - SIMPLE ASSAULT,0416 2000 0913 0444,...,IC,Invest Cont,624.0,NaN,NaN,NaN,VERNON AV,ALAMEDA ST,34.0039,-118.2392
84112,202115274,2020-10-25,2020-10-24,2345,21,Topanga,2139,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,7400 WINNETKA AV,NaN,34.2047,-118.5710

In [8]:
df = df[df["Crm Cd"] == df["Crm Cd 1"]]
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,201516407,2020-10-17,2020-10-15,2100,15,N Hollywood,1581,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4300 WHITSETT AV,NaN,34.1486,-118.4052
1,200700622,2020-03-24,2020-03-24,1430,7,Wilshire,705,626,INTIMATE PARTNER - SIMPLE ASSAULT,0416 1814 1402,...,AA,Adult Arrest,626.0,998.0,NaN,NaN,800 N ALTA VISTA BL,NaN,34.0853,-118.3475
2,200312712,2020-06-14,2020-06-14,1030,3,Southwest,362,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1251 1259 2024 1815 0554 0334 0913 0400 1402,...,JA,Juv Arrest,230.0,NaN,NaN,NaN,4600 OBAMA BL,NaN,34.0170,-118.3477
3,201515083,2020-09-12,2020-09-08,1528,15,N Hollywood,1585,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0325 0216,...,IC,Invest Cont,341.0,NaN,NaN,NaN,11200 W VENTURA BL,NaN,34.1430,-118.3727
4,200817552,2020-12-14,2020-12-14,805,8,West LA,853,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1822,...,AA,Adult Arrest,740.0,NaN,NaN,NaN,BARRINGTON,NEBRASKA,34.0445,-118.4491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84108,201207833,2020-02-25,2020-02-25,2100,12,77th Street,1211,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1822 0400 0411 0906,...,IC,Invest Cont,230.0,NaN,NaN,NaN,SLAUSON AV,7TH AV,33.9891,-118.3247
84109,201208587,2020-03-06,2020-03-06,920,12,77th Street,1273,626,INTIMATE PARTNER - SIMPLE ASSAULT,2000 0913 1813 0337 0444,...,IC,Invest Cont,626.0,NaN,NaN,NaN,2000 W MANCHESTER AV,NaN,33.9600,-118.3134
84110,201819827,2020-10-31,2020-10-31,30,18,Southeast,1842,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1822 1300 1309 0416 0400 1206 2033,...,IC,Invest Cont,230.0,NaN,NaN,NaN,111TH ST,SAN PEDRO,33.9348,-118.2695
84111,221319440,2022-10-17,2020-05-14,2100,13,Newton,1367,624,BATTERY - SIMPLE ASSAULT,0416 2000 0913 0444,...,IC,Invest Cont,624.0,NaN,NaN,NaN,VERNON AV,ALAMEDA ST,34.0039,-118.2392
84112,202115274,2020-10-25,2020-10-24,2345,21,Topanga,2139,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,7400 WINNETKA AV,NaN,34.2047,-118.5710

In [10]:
X = df.drop(columns=["Crm Cd"])
y = df["Crm Cd"]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
print(len(X_train), len(X_val), len(X_test))

67268 16818 9346

In [12]:
X_train

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd Desc,Mocodes,Vict Age,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
4230,200806655,2020-02-28,2020-02-05,1000,8,West LA,896,THEFT OF IDENTITY,0100 0929 1822,55,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9800 NATIONAL BL,NaN,34.0314,-118.3998
43506,200613355,2020-07-29,2020-06-21,30,6,Hollywood,647,BURGLARY,1609 0344,0,...,IC,Invest Cont,310.0,NaN,NaN,NaN,1500 ARGYLE AV,NaN,34.0980,-118.3251
13891,201113547,2020-09-13,2020-09-13,1200,11,Northeast,1113,VEHICLE - STOLEN,NaN,0,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4700 ROUND TOP DR,NaN,34.1333,-118.2288
29569,200315866,2020-08-16,2020-08-16,1310,3,Southwest,362,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329,30,...,IC,Invest Cont,745.0,NaN,NaN,NaN,4800 W MARTIN LUTHER KING JR BL,NaN,34.0170,-118.3477
7838,201409906,2020-04-21,2020-04-21,1830,14,Pacific,1427,BATTERY - SIMPLE ASSAULT,0400,51,...,IC,Invest Cont,624.0,NaN,NaN,NaN,3400 S SEPULVEDA BL,NaN,34.0212,-118.4238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6266,210406452,2021-03-09,2020-04-16,1830,4,Hollenbeck,457,THEFT OF IDENTITY,0100,35,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2400 BOULDER ST,NaN,34.0492,-118.2055
54901,202014789,2020-09-17,2020-09-17,1600,20,Olympic,2091,THEFT PLAIN - PETTY ($950 & UNDER),0913 1814 0344 2004 1218,23,...,AO,Adult Other,440.0,NaN,NaN,NaN,MANHATTAN BL,20TH ST,34.0388,-118.3098
76846,200518400,2020-12-31,2020-12-31,600,5,Harbor,524,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329 2000 0913 1814 1309,43,...,AO,Adult Other,745.0,NaN,NaN,NaN,G ST,KING AV,33.7778,-118.2754
860,202006921,2020-03-02,2020-03-02,700,20,Olympic,2088,INTIMATE PARTNER - SIMPLE ASSAULT,0913 1814 0446 0416 0329 2001 2000,42,...,AO,Adult Other,626.0,NaN,NaN,NaN,1700 S NEW ENGLAND ST,NaN,34.0431,-118.2877
15799,201422042,2020-12-23,2020-12-23,330,14,Pacific,1424,BURGLARY,0344 0397,54,...,IC,Invest Cont,310.0,NaN,NaN,NaN,3100 GRANVILLE AV,NaN,34.0201,-118.4389

In [14]:
X_train.drop(columns=["DR_NO", "AREA NAME", "Status Desc", "Weapon Desc", "Premis Desc", "Crm Cd Desc", "Crm Cd 1", "Crm Cd 2", "Crm Cd 3", "Crm Cd 4"], inplace=True)
X_val.drop(columns=["DR_NO", "AREA NAME", "Status Desc", "Weapon Desc", "Premis Desc", "Crm Cd Desc", "Crm Cd 1", "Crm Cd 2", "Crm Cd 3", "Crm Cd 4"], inplace=True)
X_test.drop(columns=["DR_NO", "AREA NAME", "Status Desc", "Weapon Desc", "Premis Desc"], inplace=True)
X_train

,Date Rptd,DATE OCC,TIME OCC,AREA,Rpt Dist No,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Weapon Used Cd,Status,LOCATION,Cross Street,LAT,LON
4230,2020-02-28,2020-02-05,1000,8,896,0100 0929 1822,55,F,B,502.0,NaN,IC,9800 NATIONAL BL,NaN,34.0314,-118.3998
43506,2020-07-29,2020-06-21,30,6,647,1609 0344,0,M,W,203.0,NaN,IC,1500 ARGYLE AV,NaN,34.0980,-118.3251
13891,2020-09-13,2020-09-13,1200,11,1113,NaN,0,NaN,NaN,101.0,NaN,IC,4700 ROUND TOP DR,NaN,34.1333,-118.2288
29569,2020-08-16,2020-08-16,1310,3,362,0329,30,M,B,502.0,NaN,IC,4800 W MARTIN LUTHER KING JR BL,NaN,34.0170,-118.3477
7838,2020-04-21,2020-04-21,1830,14,1427,0400,51,M,H,203.0,400.0,IC,3400 S SEPULVEDA BL,NaN,34.0212,-118.4238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6266,2021-03-09,2020-04-16,1830,4,457,0100,35,F,H,101.0,NaN,IC,2400 BOULDER ST,NaN,34.0492,-118.2055
54901,2020-09-17,2020-09-17,1600,20,2091,0913 1814 0344 2004 1218,23,F,H,102.0,NaN,AO,MANHATTAN BL,20TH ST,34.0388,-118.3098
76846,2020-12-31,2020-12-31,600,5,524,0329 2000 0913 1814 1309,43,F,H,101.0,NaN,AO,G ST,KING AV,33.7778,-118.2754
860,2020-03-02,2020-03-02,700,20,2088,0913 1814 0446 0416 0329 2001 2000,42,M,H,501.0,400.0,AO,1700 S NEW ENGLAND ST,NaN,34.0431,-118.2877
15799,2020-12-23,2020-12-23,330,14,1424,0344 0397,54,F,W,501.0,500.0,IC,3100 GRANVILLE AV,NaN,34.0201,-118.4389

In [16]:
print(len(y_train.unique()))
print(y_train.value_counts())

15
Crm Cd
510    8948
624    7048
330    5593
740    5518
310    5434
230    4986
440    4629
626    4622
420    4205
354    4039
745    2991
210    2985
341    2365
331    2073
930    1832
Name: count, dtype: int64

In [18]:
X_train_null_count_by_column = X_train.isnull().sum()
X_train_null_count_by_column[X_train_null_count_by_column > 0]

Mocodes           10987
Vict Sex          10812
Vict Descent      10813
Premis Cd             1
Weapon Used Cd    43489
Cross Street      55163
dtype: int64

In [20]:
X_val_null_count_by_column = X_val.isnull().sum()
X_val_null_count_by_column[X_val_null_count_by_column > 0]

Mocodes            2757
Vict Sex           2710
Vict Descent       2710
Premis Cd             1
Weapon Used Cd    10894
Cross Street      13722
dtype: int64

In [22]:
X_test_null_count_by_column = X_test.isnull().sum()
X_test_null_count_by_column[X_test_null_count_by_column > 0]

Mocodes           1541
Vict Sex          1516
Vict Descent      1516
Weapon Used Cd    6067
Cross Street      7737
dtype: int64

In [24]:
mask = X_train['Premis Cd'].notna()
X_train = X_train[mask]
y_train = y_train[mask]

mask = X_val['Premis Cd'].notna()
X_val = X_val[mask]
y_val = y_val[mask]

mask = X_test['Premis Cd'].notna()
X_test = X_test[mask]

In [26]:
temp = X_train["Weapon Used Cd"]
print(len(temp[~temp.isnull()]), len(temp[~temp.isnull()].unique()))

23779 69

In [28]:
temp = X_train["Vict Sex"]
print(len(temp[~temp.isnull()]), len(temp[~temp.isnull()].unique()))

56456 4

In [30]:
temp = X_train["Vict Descent"]
print(len(temp[~temp.isnull()]), len(temp[~temp.isnull()].unique()))

56455 19

In [32]:
temp = X_train["Cross Street"]
print(len(temp[~temp.isnull()]), len(temp[~temp.isnull()].unique()))

12105 3253

In [34]:
temp = X_train["LOCATION"]
print(len(temp[~temp.isnull()]), len(temp[~temp.isnull()].unique()))

67267 26530

In [36]:
temp = X_train["Mocodes"]
print(len(temp[~temp.isnull()]), len(temp[~temp.isnull()].unique()))

56281 28665

In [38]:
X_train['Mocodes']

4230                         0100 0929 1822
43506                             1609 0344
13891                                   NaN
29569                                  0329
7838                                   0400
                        ...
6266                                   0100
54901              0913 1814 0344 2004 1218
76846              0329 2000 0913 1814 1309
860      0913 1814 0446 0416 0329 2001 2000
15799                             0344 0397
Name: Mocodes, Length: 67267, dtype: object

In [40]:
mlb = MultiLabelBinarizer()

X_train['Mocodes'] = X_train['Mocodes'].astype('str').apply(lambda x: list(map(int, x.split())) if x != 'nan' else [])
X_val['Mocodes'] = X_val['Mocodes'].astype('str').apply(lambda x: list(map(int, x.split())) if x != 'nan' else [])
X_test['Mocodes'] = X_test['Mocodes'].astype('str').apply(lambda x: list(map(int, x.split())) if x != 'nan' else [])

X_train = pd.concat([X_train.reset_index(drop=True), pd.DataFrame(mlb.fit_transform(X_train["Mocodes"]), columns=[f'Mocodes_{num}' for num in mlb.classes_])], axis=1)
X_val = pd.concat([X_val.reset_index(drop=True), pd.DataFrame(mlb.transform(X_val["Mocodes"]), columns=[f'Mocodes_{num}' for num in mlb.classes_])], axis=1)
X_test = pd.concat([X_test.reset_index(drop=True), pd.DataFrame(mlb.transform(X_test["Mocodes"]), columns=[f'Mocodes_{num}' for num in mlb.classes_])], axis=1)
X_train

C:\Users\Webhouse\AppData\Local\Temp\ipykernel_5296\3970650154.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Mocodes'] = X_train['Mocodes'].astype('str').apply(lambda x: list(map(int, x.split())) if x != 'nan' else [])
C:\Users\Webhouse\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:900: UserWarning: unknown class(es) [1017, 1201, 1208, 1229, 1233, 1235, 1247, 1280, 1411, 205, 2157, 2208, 2231, 3011, 3034, 318, 343, 350, 388, 393, 4010, 414, 436, 545, 901] will be ignored
  warnings.warn(
C:\Users\Webhouse\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:900: UserWarning: unknown class(es) [1025, 108, 1233, 1235, 1531, 2008, 2013, 2022, 414, 423, 434, 436, 501, 546] will be ignored
  warnings.warn(

,Date Rptd,DATE OCC,TIME OCC,AREA,Rpt Dist No,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,...,Mocodes_3101,Mocodes_3401,Mocodes_3602,Mocodes_3701,Mocodes_4005,Mocodes_4006,Mocodes_4016,Mocodes_4025,Mocodes_4026,Mocodes_9999
0,2020-02-28,2020-02-05,1000,8,896,"[100, 929, 1822]",55,F,B,502.0,...,0,0,0,0,0,0,0,0,0,0
1,2020-07-29,2020-06-21,30,6,647,"[1609, 344]",0,M,W,203.0,...,0,0,0,0,0,0,0,0,0,0
2,2020-09-13,2020-09-13,1200,11,1113,[],0,NaN,NaN,101.0,...,0,0,0,0,0,0,0,0,0,0
3,2020-08-16,2020-08-16,1310,3,362,[329],30,M,B,502.0,...,0,0,0,0,0,0,0,0,0,0
4,2020-04-21,2020-04-21,1830,14,1427,[400],51,M,H,203.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67262,2021-03-09,2020-04-16,1830,4,457,[100],35,F,H,101.0,...,0,0,0,0,0,0,0,0,0,0
67263,2020-09-17,2020-09-17,1600,20,2091,"[913, 1814, 344, 2004, 1218]",23,F,H,102.0,...,0,0,0,0,0,0,0,0,0,0
67264,2020-12-31,2020-12-31,600,5,524,"[329, 2000, 913, 1814, 1309]",43,F,H,101.0,...,0,0,0,0,0,0,0,0,0,0
67265,2020-03-02,2020-03-02,700,20,2088,"[913, 1814, 446, 416, 329, 2001, 2000]",42,M,H,501.0,...,0,0,0,0,0,0,0,0,0,0
67266,2020-12-23,2020-12-23,330,14,1424,"[344, 397]",54,F,W,501.0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
X_train.drop(columns=["Cross Street", "LOCATION", "Mocodes"], inplace=True)
X_val.drop(columns=["Cross Street", "LOCATION", "Mocodes"], inplace=True)
X_test.drop(columns=["Cross Street", "LOCATION", "Mocodes"], inplace=True)
X_train

,Date Rptd,DATE OCC,TIME OCC,AREA,Rpt Dist No,Vict Age,Vict Sex,Vict Descent,Premis Cd,Weapon Used Cd,...,Mocodes_3101,Mocodes_3401,Mocodes_3602,Mocodes_3701,Mocodes_4005,Mocodes_4006,Mocodes_4016,Mocodes_4025,Mocodes_4026,Mocodes_9999
0,2020-02-28,2020-02-05,1000,8,896,55,F,B,502.0,NaN,...,0,0,0,0,0,0,0,0,0,0
1,2020-07-29,2020-06-21,30,6,647,0,M,W,203.0,NaN,...,0,0,0,0,0,0,0,0,0,0
2,2020-09-13,2020-09-13,1200,11,1113,0,NaN,NaN,101.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3,2020-08-16,2020-08-16,1310,3,362,30,M,B,502.0,NaN,...,0,0,0,0,0,0,0,0,0,0
4,2020-04-21,2020-04-21,1830,14,1427,51,M,H,203.0,400.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67262,2021-03-09,2020-04-16,1830,4,457,35,F,H,101.0,NaN,...,0,0,0,0,0,0,0,0,0,0
67263,2020-09-17,2020-09-17,1600,20,2091,23,F,H,102.0,NaN,...,0,0,0,0,0,0,0,0,0,0
67264,2020-12-31,2020-12-31,600,5,524,43,F,H,101.0,NaN,...,0,0,0,0,0,0,0,0,0,0
67265,2020-03-02,2020-03-02,700,20,2088,42,M,H,501.0,400.0,...,0,0,0,0,0,0,0,0,0,0
67266,2020-12-23,2020-12-23,330,14,1424,54,F,W,501.0,500.0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
str_cols = ["Vict Sex", "Vict Descent", "Status"]
encoder = OrdinalEncoder()
X_train[str_cols] = encoder.fit_transform(X_train[str_cols])
X_val[str_cols] = encoder.transform(X_val[str_cols])
X_test[str_cols] = encoder.transform(X_test[str_cols])
X_train

,Date Rptd,DATE OCC,TIME OCC,AREA,Rpt Dist No,Vict Age,Vict Sex,Vict Descent,Premis Cd,Weapon Used Cd,...,Mocodes_3101,Mocodes_3401,Mocodes_3602,Mocodes_3701,Mocodes_4005,Mocodes_4006,Mocodes_4016,Mocodes_4025,Mocodes_4026,Mocodes_9999
0,2020-02-28,2020-02-05,1000,8,896,55,0.0,1.0,502.0,NaN,...,0,0,0,0,0,0,0,0,0,0
1,2020-07-29,2020-06-21,30,6,647,0,2.0,16.0,203.0,NaN,...,0,0,0,0,0,0,0,0,0,0
2,2020-09-13,2020-09-13,1200,11,1113,0,NaN,NaN,101.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3,2020-08-16,2020-08-16,1310,3,362,30,2.0,1.0,502.0,NaN,...,0,0,0,0,0,0,0,0,0,0
4,2020-04-21,2020-04-21,1830,14,1427,51,2.0,6.0,203.0,400.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67262,2021-03-09,2020-04-16,1830,4,457,35,0.0,6.0,101.0,NaN,...,0,0,0,0,0,0,0,0,0,0
67263,2020-09-17,2020-09-17,1600,20,2091,23,0.0,6.0,102.0,NaN,...,0,0,0,0,0,0,0,0,0,0
67264,2020-12-31,2020-12-31,600,5,524,43,0.0,6.0,101.0,NaN,...,0,0,0,0,0,0,0,0,0,0
67265,2020-03-02,2020-03-02,700,20,2088,42,2.0,6.0,501.0,400.0,...,0,0,0,0,0,0,0,0,0,0
67266,2020-12-23,2020-12-23,330,14,1424,54,0.0,16.0,501.0,500.0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
X_train["Rptd_OCC_Diff"] = (X_train["Date Rptd"] - X_train["DATE OCC"]).dt.days
X_val["Rptd_OCC_Diff"] = (X_val["Date Rptd"] - X_val["DATE OCC"]).dt.days
X_test["Rptd_OCC_Diff"] = (X_test["Date Rptd"] - X_test["DATE OCC"]).dt.days

X_train.drop(columns=["Date Rptd"], inplace=True)
X_val.drop(columns=["Date Rptd"], inplace=True)
X_test.drop(columns=["Date Rptd"], inplace=True)

In [48]:
print(X_train["DATE OCC"].dt.year.unique())
print(X_train["DATE OCC"].dt.month.unique())

[2020]
[ 2  6  9  8  4  5  7 12  3 10  1 11]

In [50]:
X_train["Month OCC"] = X_train["DATE OCC"].dt.month
X_val["Month OCC"] = X_val["DATE OCC"].dt.month
X_test["Month OCC"] = X_test["DATE OCC"].dt.month

X_train.drop(columns=["DATE OCC"], inplace=True)
X_val.drop(columns=["DATE OCC"], inplace=True)
X_test.drop(columns=["DATE OCC"], inplace=True)

In [52]:
scaler = StandardScaler()

X_train = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_val = pd.DataFrame(
    scaler.transform(X_val),
    columns=X_val.columns,
    index=X_val.index
)

X_test = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)
X_train

,TIME OCC,AREA,Rpt Dist No,Vict Age,Vict Sex,Vict Descent,Premis Cd,Weapon Used Cd,Status,LAT,...,Mocodes_3602,Mocodes_3701,Mocodes_4005,Mocodes_4006,Mocodes_4016,Mocodes_4025,Mocodes_4026,Mocodes_9999,Rptd_OCC_Diff,Month OCC
0,-0.549442,-0.471098,-0.387780,1.127658,-1.168962,-1.355055,1.049348,NaN,0.448279,0.022230,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,0.029893,-1.279540
1,-2.036061,-0.804098,-0.802285,-1.383317,0.681216,1.185847,-0.360673,NaN,0.448279,0.062898,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,0.167466,-0.122993
2,-0.242923,0.028403,-0.026545,-1.383317,NaN,NaN,-0.841684,NaN,0.448279,0.084454,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,0.744418
3,-0.074337,-1.303599,-1.276718,-0.013694,0.681216,-1.355055,1.049348,NaN,0.448279,0.013437,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,0.455281
4,0.722613,0.527904,0.496163,0.945042,0.681216,-0.508087,-0.360673,0.245799,0.448279,0.016001,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,-0.701267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67262,0.722613,-1.137099,-1.118573,0.214576,-1.168962,-0.508087,-0.841684,NaN,0.448279,0.033099,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,2.818050,-0.701267
67263,0.370116,1.526905,1.601509,-0.333273,-1.168962,-0.508087,-0.836968,NaN,-1.149557,0.026749,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,0.744418
67264,-1.162481,-0.970598,-1.007040,0.579809,-1.168962,-0.508087,-0.841684,NaN,-1.149557,-0.132627,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,1.611828
67265,-1.009221,1.526905,1.596515,0.534155,0.681216,-0.508087,1.044633,0.245799,-1.149557,0.029374,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,-0.990403
67266,-1.576282,0.527904,0.491169,1.082004,-1.168962,1.185847,1.044633,1.100202,0.448279,0.015330,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,1.611828

In [54]:
imputer = SimpleImputer(strategy="most_frequent")
X_train = pd.DataFrame(
    imputer.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_val = pd.DataFrame(
    imputer.transform(X_val),
    columns=X_val.columns,
    index=X_val.index
)

X_test = pd.DataFrame(
    imputer.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)
X_train

,TIME OCC,AREA,Rpt Dist No,Vict Age,Vict Sex,Vict Descent,Premis Cd,Weapon Used Cd,Status,LAT,...,Mocodes_3602,Mocodes_3701,Mocodes_4005,Mocodes_4006,Mocodes_4016,Mocodes_4025,Mocodes_4026,Mocodes_9999,Rptd_OCC_Diff,Month OCC
0,-0.549442,-0.471098,-0.387780,1.127658,-1.168962,-1.355055,1.049348,0.245799,0.448279,0.022230,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,0.029893,-1.279540
1,-2.036061,-0.804098,-0.802285,-1.383317,0.681216,1.185847,-0.360673,0.245799,0.448279,0.062898,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,0.167466,-0.122993
2,-0.242923,0.028403,-0.026545,-1.383317,0.681216,-0.508087,-0.841684,0.245799,0.448279,0.084454,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,0.744418
3,-0.074337,-1.303599,-1.276718,-0.013694,0.681216,-1.355055,1.049348,0.245799,0.448279,0.013437,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,0.455281
4,0.722613,0.527904,0.496163,0.945042,0.681216,-0.508087,-0.360673,0.245799,0.448279,0.016001,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,-0.701267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67262,0.722613,-1.137099,-1.118573,0.214576,-1.168962,-0.508087,-0.841684,0.245799,0.448279,0.033099,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,2.818050,-0.701267
67263,0.370116,1.526905,1.601509,-0.333273,-1.168962,-0.508087,-0.836968,0.245799,-1.149557,0.026749,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,0.744418
67264,-1.162481,-0.970598,-1.007040,0.579809,-1.168962,-0.508087,-0.841684,0.245799,-1.149557,-0.132627,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,1.611828
67265,-1.009221,1.526905,1.596515,0.534155,0.681216,-0.508087,1.044633,0.245799,-1.149557,0.029374,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,-0.990403
67266,-1.576282,0.527904,0.491169,1.082004,-1.168962,1.185847,1.044633,1.100202,0.448279,0.015330,...,-0.003856,-0.008622,-0.003856,-0.003856,-0.003856,-0.007712,-0.003856,-0.02314,-0.181053,1.611828

In [56]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_val_pred = model.predict(X_val)

print("F1 (train):", f1_score(y_train, y_train_pred, average="macro"))
print("F1 (val)  :", f1_score(y_val, y_val_pred, average="macro"))

F1 (train): 0.9999595075669032
F1 (val)  : 0.714125191456011

In [63]:
submission = pd.DataFrame({"Crm Cd": model.predict(X_test)})
submission

      Crm Cd
0        230
1        626
2        310
3        624
4        740
...      ...
9341     210
9342     745
9343     930
9344     740
9345     626

[9346 rows x 1 columns]

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) در غیر این صورت، در پایان مسابقه نمره شما به صفر تغییر خواهد کرد.
    <br>
    همچنین اگر از کولب برای اجرای این فایل نوت‌بوک استفاده می‌کنید، قبل از ارسال فایل <code>result.zip</code>، آخرین نسخه‌ی نوت‌بوک خود را دانلود کرده و داخل فایل ارسالی قرار دهید.
</font>

In [65]:
import zipfile
import joblib
import os

if not os.path.exists(os.path.join(os.getcwd(), 'crime-detection.ipynb')):
    %notebook crime-detection.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['crime-detection.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['crime-detection.ipynb', 'submission.csv']